name: Build Vue
on:
  push:
    branches: ["main"]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "ppabimanyu"
          reponame: "tugas-vuejs-stechoq2"
          token: ${{ secrets.GH_TOKEN }} # Leave this line unchanged
